import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { type DiagnosisResponse, type Vitals, type Demographics } from '../services/geminiService';

export const generatePDFReport = (
  result: DiagnosisResponse,
  symptoms: string[],
  vitals: Vitals,
  demographics: Demographics
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(16, 185, 129); // Emerald-600
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MediSense AI', 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Preliminary Diagnostic Assessment Report', 20, 32);

  // Date
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.setFontSize(10);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth - 20, 50, { align: 'right' });

  // Patient Information Section
  doc.setTextColor(15, 23, 42); // Slate-900
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Information', 20, 60);
  
  const patientData = [
    ['Age', demographics.age || 'Not provided'],
    ['Gender', demographics.gender || 'Not provided'],
    ['Pre-existing Conditions', demographics.preExistingConditions || 'None reported']
  ];

  autoTable(doc, {
    startY: 65,
    head: [],
    body: patientData,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
  });

  // Vitals Section
  let currentY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Clinical Vitals', 20, currentY);

  const vitalsData = [
    ['Temperature', vitals.temperature ? `${vitals.temperature}°C` : 'Not provided'],
    ['Blood Pressure', vitals.bloodPressure || 'Not provided'],
    ['Heart Rate', vitals.heartRate ? `${vitals.heartRate} bpm` : 'Not provided'],
    ['Oxygen Saturation (SpO2)', vitals.spO2 ? `${vitals.spO2}%` : 'Not provided']
  ];

  autoTable(doc, {
    startY: currentY + 5,
    head: [],
    body: vitalsData,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
  });

  // Symptoms Section
  currentY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Reported Symptoms', 20, currentY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(symptoms.join(', '), 20, currentY + 7, { maxWidth: pageWidth - 40 });

  // AI Summary
  currentY = currentY + 20;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Assessment Summary', 20, currentY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text(`"${result.summary}"`, 20, currentY + 7, { maxWidth: pageWidth - 40 });

  // Possible Conditions Table
  currentY = currentY + 30;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Possible Conditions', 20, currentY);

  const conditionsData = result.possibleConditions.map(c => [
    c.condition,
    c.probability,
    c.urgency,
    c.nextSteps.join('\n')
  ]);

  autoTable(doc, {
    startY: currentY + 5,
    head: [['Condition', 'Match', 'Urgency', 'Recommended Next Steps']],
    body: conditionsData,
    headStyles: { fillColor: [16, 185, 129] },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 3: { cellWidth: 60 } }
  });

  // Footer Disclaimer
  const footerY = doc.internal.pageSize.getHeight() - 30;
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.line(20, footerY, pageWidth - 20, footerY);
  
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'italic');
  doc.text('IMPORTANT MEDICAL DISCLAIMER:', 20, footerY + 7);
  doc.text(result.disclaimer, 20, footerY + 12, { maxWidth: pageWidth - 40 });
  
  doc.setFont('helvetica', 'normal');
  doc.text('This report was generated by MediSense AI and is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.', 20, footerY + 22, { maxWidth: pageWidth - 40 });

  doc.save(`MediSense_Report_${new Date().getTime()}.pdf`);
};
